server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:trackingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    enabled: true
    version: OPENAPI_3_0 # ✅ Explicitly specify OpenAPI version
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
